### ISSUE TITLE
Inconsistent "content" values

### ISSUE THREAD

**Issue by heyjones** [itgalaxy/webfont-webpack-plugin#73] opened 2017-08-10 17:36 UTC
Whenever the css is generated, it seems that the `content` values are varying slightly. So when I try to use the unicode values in my css the icons are swapping around. I tried setting `descent: 0` thinking that would force the icons to sort the svg assets alphabetically but that doesn't seem to be the case. What's the best way to ensure consistent unicode content values across builds?

**Comment by heyjones** [comment] 2017-08-10 21:51
It seems like this isn't sorting them properly:

https://github.com/itgalaxy/webfont/blob/master/src/standalone.js#L27

**Comment by evilebottnawi** [comment] 2017-08-11 08:39
@heyjones thanks for issue, yep, i think it is related to `webfont`, can your create issue there and provide minimum reproducible test repo, thanks!

**Comment by dudewad** [comment] 2017-09-04 00:39
@heyjones I thought this was a problem but I think it's actually not... assuming our problems are the same.
My experience is that yes, the `content` values change (the unicode value changes, I assume because `webfont` at the core uses an object and iterates through it which is not necessarily in order). The subsequent unicode character changes, however, are properly propagated to the resulting CSS file (from what I can tell, anyways) - in other words, despite the changes to both the font file itself and the CSS output (or scss or whatever you use), the resulting output matches as it should. The problem I have is that Webpack is not re-compiling the new changes properly, which causes breakage because the new font files get consumed by the browser but my SCSS is not being updated. @evilebottnawi I just opened an infinite recompile issue that I'm experiencing alongside this issue.. not sure if they are related (doesn't seem like it but I thought I'd point them out).

**Comment by dudewad** [comment] 2017-09-13 22:47
@heyjones ^ping on the above comment :)

**Comment by dudewad** [comment] 2017-09-14 02:02
Okay so after #77 gets merged (infinite compilation fix) this still is an issue, although it is _partially_ solved. The cause of the issue seems to be 2 things (prior to the merging of #77):

 - Because of the known issue of having to ignore generated font files to avoid the infinite recompile, Webpack will therefore never recompile the font on changes. This is what #77 fixes.
 - Once #77 is merged, it will still be an issue because of the fact that the assets are cached by the browser. We could implement something like hashing to force a new download (particularly in the dev server) because I noticed that clearing cache now fixes the issue with my local fixes for the other issue. I haven't looked into how to do this outside of manually doing it via the `webfont` package but I don't really want to reach that far back to do something as simple as a cache refresh.

@evilebottnawi what are your thoughts on that?

**Comment by evilebottnawi** [comment] 2017-09-14 08:34
@dudewad in fact, caching must be implemented `webfont`, i don't have time now for this, but we can use https://github.com/zkat/cacache or https://github.com/royriojas/flat-cache (better) for this, it should be very easy to implement.

Also, I would like to repeat that the solution was to make this plugin not quite right, it should be as loader. It is allow to use `webpack` cache, also it is allow to avoid problem with infinity loop. When I wrote this plugin I did not understand well `webpack` architecture, now my knowledge is better :smile:

**Comment by dudewad** [comment] 2017-09-14 17:47
It sounds like you made that decision when you knew about as much as I know now! I'd love to see the loader version someday. If there's any way I can help I'd like to -- I want to learn webpack better and the docs aren't helping much!

**Comment by evilebottnawi** [comment] 2017-09-18 09:17
@dudewad let's merge, but without test it is very dangeour

**Comment by dudewad** [comment] 2017-09-19 01:02
@evilebottnawi I am fine waiting for test. For what it is worth, my current version is not having any issues. I'd rather you run tests so that we don't run into issues... but it sounds like you don't have time?  :/

**Comment by dudewad** [comment] 2017-09-19 01:06
Oh, and FYI, I don't have access to merge :) You'll have to do it.

**Comment by wasa4587** [comment] 2017-11-15 18:29
I fixed this, setting the `maxConcurrency` to `1`,
so it uses only 1 core of your CPU, and the content values are always the same
`      new WebfontPlugin({
          files: helpers.root('src/assets/svg/*.svg'),
          css: true,
          maxConcurrency: 1,
          template: 'css',
          fontName: 'webfont',
          cssTemplateFontPath: `${getAssetsPath(isProd)}/fonts/`,
          dest: {
              fontsDir: helpers.root('src/assets/fonts/'),
              stylesDir: helpers.root('src/assets/css/')
          }
      })`

**Comment by dudewad** [comment] 2017-11-15 18:41
Beautiful! I'll give that a try... no time right now but when I get around to it I'll try to confirm that.

**Comment by evilebottnawi** [comment] 2018-05-02 15:45
Fixed in `webfont`, just update to latest version. Thanks!

**Closed by evilebottnawi** 2018-05-02 15:45 UTC

**Comment by dudewad** [comment] 2018-05-03 00:01
Fantastic!! Thanks!

**Comment by evilebottnawi** [comment] 2018-05-03 09:07
Sorry for delay, a lot of work
